ARG NODE_VERSION=24.13.0
FROM node:${NODE_VERSION}-slim AS base

WORKDIR /app


FROM base AS prepare

RUN npm install -g turbo
COPY ./apps/web/out ./out


FROM base AS builder

# copy package*.json struture
COPY --from=prepare /app/out/json/ .
RUN npm ci

ARG VITE_KEYCLOAK_URL
ARG VITE_KEYCLOAK_REALM
ARG VITE_KEYCLOAK_CLIENT_ID
ARG VITE_BACKEND_URL

ENV VITE_KEYCLOAK_URL=$VITE_KEYCLOAK_URL
ENV VITE_KEYCLOAK_REALM=$VITE_KEYCLOAK_REALM
ENV VITE_KEYCLOAK_CLIENT_ID=$VITE_KEYCLOAK_CLIENT_ID
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL

# copy all files except node_module and builds
COPY --from=prepare /app/out/full/ .
RUN npm run build --filter=@repo/shared-types
RUN npm run build --workspace apps/web


FROM base AS runner

COPY --from=builder /app .

CMD ["npm", "run", "preview", "--workspace", "apps/web"]