# Stage 1: build
FROM node:20-alpine AS builder
WORKDIR /monorepo

COPY package*.json ./
COPY apps/frontend/package*.json apps/frontend/
COPY packages/shared-types/package*.json packages/shared-types/

COPY packages ./packages
COPY apps/frontend ./apps/frontend

RUN npm install
RUN npm run build --workspace apps/frontend

# Stage 2: runtime
FROM node:20-alpine
WORKDIR /monorepo/apps/frontend
COPY --from=builder /monorepo/apps/frontend/package*.json ./
COPY --from=builder /monorepo/apps/frontend/dist ./dist
COPY --from=builder /monorepo/node_modules ./node_modules

EXPOSE 5173
CMD ["node", "dist/index.js"]