ARG NODE_VERSION=24.13.0
FROM node:${NODE_VERSION}-slim AS base

WORKDIR /app


FROM base AS prepare

RUN npm i -g turbo
COPY . .
RUN turbo prune frontend --docker


FROM base AS builder

ARG VITE_KEYCLOAK_URL
ARG VITE_KEYCLOAK_REALM
ARG VITE_KEYCLOAK_CLIENT_ID
ARG VITE_BACKEND_URL

ENV VITE_KEYCLOAK_URL=$VITE_KEYCLOAK_URL
ENV VITE_KEYCLOAK_REALM=$VITE_KEYCLOAK_REALM
ENV VITE_KEYCLOAK_CLIENT_ID=$VITE_KEYCLOAK_CLIENT_ID
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL

# First install dependencies (as they change less often)
COPY --from=prepare /app/out/json/ .
RUN npm install

# Build the project and its dependencies
COPY --from=prepare /app/out/full/ .

RUN npm run build --filter=@repo/shared-types
RUN npm run build --workspace apps/frontend


FROM base AS runner

# Don't run production as root
COPY --from=builder /app/apps/frontend .

CMD ["npm", "run", "preview"]
