ARG NODE_VERSION=24.13.0
FROM node:${NODE_VERSION}-slim AS base

WORKDIR /app


FROM base AS prepare

RUN npm install -g turbo
COPY ./apps/admin/out ./out


FROM base AS builder

# copy package*.json struture
COPY --from=prepare /app/out/json/ .
RUN npm ci

# copy all files except node_module and builds
COPY --from=prepare /app/out/full/ .
RUN npm run build --filter=@repo/shared-types


FROM base AS runner

COPY --from=builder /app .

# RUN apt-get update && apt-get install -y tree
# RUN tree -L 3

CMD ["npm", "run", "dev", "--workspace", "apps/admin"]
