ARG NODE_VERSION=24.13.0
FROM node:${NODE_VERSION}-slim AS base

WORKDIR /app


FROM base AS prepare

RUN npm install -g turbo
COPY ./apps/api/out ./out


FROM base AS builder

# copy package*.json struture
COPY --from=prepare /app/out/json/ .
RUN npm ci

# copy all files except node_module and builds
COPY --from=prepare /app/out/full/ .
RUN npm run build --filter=@repo/shared-types
RUN npm run build --workspace apps/api
RUN find . -type d -name node_modules -prune -exec rm -rf '{}' +


FROM base AS runner

COPY --from=builder /app .
RUN npm ci --omit=dev

# RUN apt-get update && apt-get install -y tree
# RUN tree -L 3

CMD ["node", "apps/api/build/index.js"]
