ARG NODE_VERSION=24.13.0
FROM node:${NODE_VERSION}-slim AS base

WORKDIR /app


FROM base AS prepare

RUN npm i -g turbo
COPY . .
RUN turbo prune api --docker


FROM base AS builder

# First install dependencies (as they change less often)
COPY --from=prepare /app/out/json/ .

RUN npm install

# Build the project and its dependencies
COPY --from=prepare /app/out/full/ .

RUN npm run build --filter=@repo/shared-types
RUN npm run build --workspace apps/api


FROM base AS runner

COPY --from=builder /app/apps/api .

CMD ["node", "build/index.js"]
