ARG NODE_VERSION=24.13.0
FROM node:${NODE_VERSION}-slim AS base

WORKDIR /app

FROM base AS prepare

RUN npm i -g turbo
COPY ./out ./out


FROM base AS builder

COPY --from=prepare /app/out/json/ .
RUN npm install

COPY --from=prepare /app/out/full/ .
RUN npm run build --filter=@repo/shared-types
RUN npm run build --workspace apps/api


FROM base AS runner

COPY --from=builder /app/apps/api .
CMD ["node", "build/index.js"]
